version: 2
builds:
  - id: bento
    main: cmd/bento/main.go
    binary: bento
    goos: [ windows, darwin, linux ]
    goarch: [ amd64, arm64 ]
    env:
      - CGO_ENABLED=0
    ldflags: >
      -s -w
      -X github.com/warpstreamlabs/bento/internal/cli.Version={{.Version}}
      -X github.com/warpstreamlabs/bento/internal/cli.DateBuilt={{.Date}}
      -X main.Version={{.Version}}
      -X main.DateBuilt={{.Date}}
archives:
  - id: bento
    builds: [ bento ]
    format: tar.gz
    files:
      - README.md
      - CHANGELOG.md
      - LICENSE
dist: target/dist
release:
  github:
    owner: warpstreamlabs
    name: bento
  prerelease: auto
  disable: false
