name: plugin_alias
type: processor
status: experimental
summary: This is a test template to check that plugin aliases work.

fields:
  - name: duration
    description: how long to sleep for.
    type: string
    default: 1s

mapping: 'root.sleep.duration = this.duration'

tests:
  - name: Basic fields
    config:
      duration: 5s
    expected:
      sleep:
        duration: 5s

  - name: Use Default
    config: {}
    expected:
      sleep:
        duration: 1s
